platform :ios, '13.0'

target 'App' do
  use_frameworks!

  # Add your dependencies here
  # pod 'SomeDependency', '~> 1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
